In [1]:
import os

os.chdir("../../src")

from utils.paths import DATA_PATH, RAW_ANNDATA_PATH, RAW_ANNDATA_FILENAME

import h5py

In [2]:
from utils import data_utils

adata = data_utils.load_anndata(mode="train")

/home/prz/bioml/.venv/lib/python3.10/site-packages/anndata/_core/anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


Subsampling anndata with fraction 1.0...


In [3]:
adata.obs.index

Index(['TCAAGCACACCGGCTA-1-s1d1', 'ACGTACAGTGAGAGGG-1-s2d5',
       'TACAACGCATAGCACT-1-s3d1', 'GTAATGCCACAGCATT-1-s3d6',
       'TCGATTTGTGTTGATC-1-s3d6', 'AGGACTTGTCATCCGG-1-s3d7',
       'CTCATGCTCGTTAGAC-1-s2d5', 'GAGCCTGCAACGTTAC-1-s2d5',
       'CATCCGTGTCGATTCA-1-s2d5', 'GGGAAGTAGTTCTCTT-1-s3d6',
       ...
       'TAGACTGCAGCTTTGA-1-s1d2', 'GCTTCACCAGAAGCTG-1-s2d1',
       'AGCCACGAGGTCCCTG-1-s2d1', 'TCACGCTAGACAACAT-1-s2d5',
       'ACATGCACATGACAAA-1-s3d1', 'GATTCTTTCATTGTTC-1-s3d6',
       'GTCGCGACAGTTCCAA-1-s3d1', 'TACGTCCTCCCTTGTG-1-s2d1',
       'TCTCAGCAGGATGAGA-1-s3d1', 'TTTCAGTGTTCATCTT-1-s3d7'],
      dtype='object', length=66175)

In [4]:
from utils.data import get_hdf5SparseDataloader, hdf5SparseDataset
from utils import dev_notebooks_utils as dev

ImportError: cannot import name 'get_hdf5SparseDataloader' from 'utils.data' (/home/prz/bioml/D4L-Hackaton/src/utils/data/__init__.py)

In [ ]:
cfg_dict = {
    "dataset_name": "GSE194122_openproblems_neurips2021_cite_BMMC_processed",
    "path": RAW_ANNDATA_PATH,
    "rowsize": 14087,
    "obs": {
        "columns": [
            {"org_name": "cell_type", "new_name": "cell_type", "tocat": True},
            {"org_name": "Site", "new_name": "site", "tocat": True},
            {"org_name": "batch", "new_name": "batch", "tocat": True},
        ]
    },
    "dataloader": {"batch_size": 4, "shuffle": True, "num_workers": 1},
}
cfg = dev.dict_to_namespace(cfg_dict)

In [ ]:
dataset = hdf5SparseDataset(cfg)
dsiter = iter(dataset)
dataset.__getitems__([4, 5])

{'data': tensor([[0.0000, 0.0000, 0.0000,  ..., 0.4870, 3.0834, 0.6951],
         [0.0000, 0.0000, 6.2530,  ..., 0.4963, 2.8557, 0.5896]]),
 'cell_type': tensor([35, 29]),
 'site': tensor([0, 0]),
 'batch': tensor([0, 0])}

In [ ]:
next(dsiter)

{'data': tensor([[0.0000, 0.0000, 0.0000,  ..., 0.1544, 0.9172, 0.6069]]),
 'cell_type': tensor([27]),
 'site': tensor([0]),
 'batch': tensor([0])}

In [ ]:
dataloader = get_hdf5SparseDataloader(cfg)

In [ ]:
x = next(iter(dataloader))

In [ ]:
x

{'data': tensor([[0.0000, 0.0000, 0.0000,  ..., 1.0819, 0.0000, 1.8658],
         [0.0000, 0.0000, 0.0000,  ..., 0.4030, 1.1345, 1.0513],
         [0.0000, 0.0000, 0.0000,  ..., 1.9237, 0.6943, 0.7484],
         [0.0000, 0.0000, 0.0000,  ..., 0.2190, 3.0937, 1.2380]]),
 'cell_type': tensor([12, 42,  8, 35]),
 'site': tensor([1, 3, 3, 0]),
 'batch': tensor([ 3, 11, 10,  0])}

In [ ]:
def print_tree(name, obj):
    print(name)
    if isinstance(obj, h5py.Group):
        for key, val in obj.items():
            print_tree(f"{name}/{key}", val)


def print_datasets(name, obj):
    if isinstance(obj, h5py.Dataset):
        print(name)

In [ ]:
with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    print_tree("dfd", f)

dfd
dfd/X
dfd/X/data
dfd/X/indices
dfd/X/indptr
dfd/layers
dfd/layers/counts
dfd/layers/counts/data
dfd/layers/counts/indices
dfd/layers/counts/indptr
dfd/obs
dfd/obs/ADT_iso_count
dfd/obs/ADT_n_antibodies_by_counts
dfd/obs/ADT_pseudotime_order
dfd/obs/ADT_total_counts
dfd/obs/DonorAge
dfd/obs/DonorBMI
dfd/obs/DonorBloodType
dfd/obs/DonorGender
dfd/obs/DonorID
dfd/obs/DonorNumber
dfd/obs/DonorRace
dfd/obs/DonorSmoker
dfd/obs/Ethnicity
dfd/obs/GEX_n_genes_by_counts
dfd/obs/GEX_pct_counts_mt
dfd/obs/GEX_phase
dfd/obs/GEX_pseudotime_order
dfd/obs/GEX_size_factors
dfd/obs/Modality
dfd/obs/QCMeds
dfd/obs/Samplename
dfd/obs/Site
dfd/obs/VendorLot
dfd/obs/__categories
dfd/obs/__categories/DonorBloodType
dfd/obs/__categories/DonorGender
dfd/obs/__categories/DonorNumber
dfd/obs/__categories/DonorRace
dfd/obs/__categories/DonorSmoker
dfd/obs/__categories/Ethnicity
dfd/obs/__categories/GEX_phase
dfd/obs/__categories/Modality
dfd/obs/__categories/QCMeds
dfd/obs/__categories/Samplename
dfd/obs/__ca

In [9]:
with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    print(f["obs"]["cell_type"][[4, 3]])

TypeError: Indexing elements must be in increasing order

In [29]:
with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    print(np.char.decode(f["obs"]["_index"][:].astype(bytes), "utf-8"))

['GCATTAGCATAAGCGG-1-s1d1' 'TACAGGTGTTAGAGTA-1-s1d1'
 'AGGATCTAGGTCTACT-1-s1d1' ... 'TCGAAGTGTGACAGGT-1-s4d9'
 'GCAGGCTGTTGCATAC-1-s4d9' 'ACGTAACAGGTCTACT-1-s4d9']


In [16]:
import torch
import numpy as np

with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    display(
        np.char.decode(
            np.apply_along_axis(
                func1d=lambda x: f["obs"]["__categories"]["cell_type"][x],
                axis=0,
                arr=f["obs"]["cell_type"][[3]],
            ),
            "utf-8",
        )
    )

TypeError: string operation on non-string array

In [11]:
with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    display(f["var"]["feature_types"][-200:])  # ["__categories"]["feature_types"][0])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int8)

In [26]:
x = [1, 3, 2, 2]
# x.sort()
# print(x)
list(set(x))
x[[0, 0]]

TypeError: list indices must be integers or slices, not list

In [15]:
import torch

torch.randn((3, 4)).sort(dim=0)[]

torch.return_types.sort(
values=tensor([[-1.6490,  0.5881, -0.6759, -0.3344],
        [-1.0630,  1.0364, -0.0158,  0.3993],
        [ 1.5529,  1.6043,  0.4916,  1.2765]]),
indices=tensor([[2, 0, 2, 2],
        [1, 2, 0, 1],
        [0, 1, 1, 0]]))

In [13]:
cfg_dict = {
    "transforms": ["normalize_total", "divide_by_nonzero_median", "log1p"],
    "groups_to_clone": ["obs", "var", "uns"],
    "read_file": {"filename": RAW_ANNDATA_FILENAME},
    "write_file": {
        "filename": "GSE194122_openproblems_neurips2021_cite_BMMC_processed_processed.h5"
    },
}
cfg = dev.dict_to_namespace(cfg_dict)
dev.preprocess_and_save_dataset(cfg)

AttributeError: 'Namespace' object has no attribute 'normalize_total'

In [ ]:
from utils.paths import PREPROCESSED_DATA_PATH

dummy_path = PREPROCESSED_DATA_PATH / "dummy.h5"

dummy_path.touch()

In [ ]:
import torch
from scipy.sparse import csr_matrix

with h5py.File(RAW_ANNDATA_PATH, "r") as f:
    # display(f["X"].items())
    data = f["X/data"][:]
    indices = f["X/indices"][:]
    indptr = f["X/indptr"][:]
    shape = f["X"].attrs["shape"]  # Assuming the shape is stored as an attribute

    sparse_matrix = csr_matrix((data, indices, indptr), shape=shape)
    # Convert the sparse matrix to a PyTorch tensor
    tensor_data = torch.tensor(sparse_matrix.toarray())

In [22]:
tensor_data

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.1544, 0.9172, 0.6069],
        [0.0000, 0.0000, 0.0000,  ..., 2.0188, 0.7291, 1.9254],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.7554, 0.4065],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.6674, 0.5650, 1.0964],
        [0.0000, 0.0000, 0.0000,  ..., 0.4595, 0.9286, 0.7388],
        [0.0000, 0.0000, 0.0000,  ..., 0.7759, 0.5327, 0.7759]])

In [32]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

print([split for split in kf.split(range(10))])

[(array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3])), (array([0, 1, 2, 3, 7, 8, 9]), array([4, 5, 6])), (array([0, 1, 2, 3, 4, 5, 6]), array([7, 8, 9]))]


In [40]:
import pandas as pd
import numpy as np

In [88]:
df = pd.DataFrame(
    np.array((["1", 2, 3], ["4", 5, 6])),
    index=["mouse", "rabbit"],
    columns=["one", "two", "three"],
)

In [64]:
df[
    df[["one", "two"]]
    .apply(lambda x: all(v in s for v, s in zip(x.values, [[1, 4], [5], [6]])), axis=1)
    .values
]

one  two  three
rabbit    4    5      6

In [62]:
all(v in s for v, s in zip(df.values[1], [[1, 4], [5], [6]]))

True

In [70]:
np.logical_not(np.array([True, False]))

array([False,  True])

In [167]:
df["one"].astype("category").cat.categories

Index(['1', '4'], dtype='object')

In [161]:
generator = np.random.default_rng()
generator.integers(low=0, high=2**32, size=2)

array([4066669334,  474567042])