In [1]:
import os

os.chdir("../src")

from utils import data_utils

import pandas as pd
import numpy as np
import anndata as ad
import scanpy as sc


pd.set_option("display.max_columns", None)

import argparse

In [2]:
adata = data_utils.load_anndata(
    mode="train",
    normalize=False,
    remove_batch_effect=False,
)

d:\dlls-hack\.venv\Lib\site-packages\anndata\_core\anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


Subsampling anndata with fraction 1.0...


In [3]:
adata_norm = data_utils.load_anndata(
    mode="train",
    normalize=True,
    remove_batch_effect=False,
)

d:\dlls-hack\.venv\Lib\site-packages\anndata\_core\anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


Subsampling anndata with fraction 1.0...


In [4]:
adata.X[:10, 40:50].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.8530548 , 0.        , 0.        , 0.        ],
       [0.        , 0.65803015, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 2.1703465 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.4799873 , 0.        ],
       [0.        , 1.2060345 , 0.6030173 , 0.        , 0.        ,
        0.6030173 , 0.        , 0.        , 1.2060345 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [5]:
adata_norm.X[:10, 40:50].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61683553, 0.        , 0.        , 0.        ],
       [0.        , 0.50563025, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.1538409 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.90825343, 0.        ],
       [0.        , 0.7911966 , 0.47188765, 0.        , 0.        ,
        0.47188765, 0.        , 0.        , 0.7911966 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [6]:
import scanpy as sc

sc.pp.log1p(adata)
adata.X[:10, 40:50].toarray()

d:\dlls-hack\.venv\Lib\site-packages\scanpy\preprocessing\_simple.py:398: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61683553, 0.        , 0.        , 0.        ],
       [0.        , 0.50563025, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.1538409 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.90825343, 0.        ],
       [0.        , 0.7911966 , 0.47188765, 0.        , 0.        ,
        0.47188765, 0.        , 0.        , 0.7911966 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [9]:
adata.X.max(), adata_norm.X.max()

(16.863785, 16.863785)

### Normalization by log1p seems to be working as expected now